# Generated by Django 2.1 on 2019-07-11 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='password',
        ),
    ]
